### ISSUE TITLE
`Domain whois data invalid.` error message when parsing whois data

### ISSUE THREAD

**Issue by solution-al** [likexian/whois-parser#31]
We are getting an error message `Domain whois data invalid.` when trying to parse whois data for domain [telia.ee](telia.ee)

Reproducible code below:

```go
package main

import (
	"fmt"
	"github.com/likexian/whois-go"
	"github.com/likexian/whois-parser-go"
)

func main() {
	if raw, rawErr := whois.Whois("telia.ee"); rawErr != nil {
		fmt.Println(rawErr)
	} else {
		fmt.Println(raw)
		if result, err := whoisparser.Parse(raw); err != nil {
			fmt.Println(err)
		} else {
			fmt.Println(result)
		}
	}
}
```

**Comment by likexian** [comment]
Parsing of `.ee` is not supported, I will fix it.

**Comment by likexian** [comment]
Hello @solution-al 
Sorry for the long delay, this has been fixed, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
