### ISSUE TITLE
.RU TLD and DNS glue records

### ISSUE THREAD

**Issue by AlexBlack772** [likexian/whois-parser#37]
Hello,

For some .RU tld domians NS address also has a glue record.

```domain:        YANDEX.RU
nserver:       ns1.yandex.ru. 213.180.193.1, 2a02:6b8::1
nserver:       ns2.yandex.ru. 93.158.134.1, 2a02:6b8:0:1::1
nserver:       ns9.z5h64q92x9.net.
state:         REGISTERED, DELEGATED, VERIFIED
...
```

At the moment it is parsed in a wrong way, glue record treats as a separate name server

```[domain] => Array
        (
            [domain] => yandex.ru
            [name_servers] => Array
                (
                    [0] => ns1.yandex.ru
                    [1] => 2a02:6b8::1
                    [2] => ns2.yandex.ru
                    [3] => 2a02:6b8:0:1::1
                    [4] => ns9.z5h64q92x9.net
                )
```

I'am ready to submit a patch, but what is the best option?

1) Filter glue records at all
2) Include glue record in one field with NS name ( "ns1.yandex.ru 2a02:6b8::1")
3) Any other option?

**Comment by likexian** [comment]
Hello @AlexBlack772 
Thanks for your feedback, for other tlds, I drop the glue records, because it is no meaning in whois.

**Comment by likexian** [comment]
Merged: https://github.com/likexian/whois-parser/pull/38

---
*If you think this repository is helpful, please share it with friends, thanks.*
