### ISSUE TITLE
.tk tld free domain response

### ISSUE THREAD

**Issue by AlexBlack772** [likexian/whois-parser#41]
I noticed that whois server for .tk tld responses for not existed domain with answer that parsed as existed domain

For example, domain aaaa.tk is not exists
```
   Domain name:
      AAAA.TK

   Organisation:
      BV Dot TK
      Dot TK administrator
      P.O. Box 11774
      1001 GT  Amsterdam
      Netherlands
      Phone: +31 20 5315725
      Fax: +31 20 5315721
      E-mail: abuse: abuse@freenom.com, copyright infringement: copyright@freenom.com

   Domain Nameservers:
      NS01.FREENOM.COM
      NS02.FREENOM.COM
      NS03.FREENOM.COM
      NS04.FREENOM.COM


   Your selected domain name is a Free Domain. That means that,
   according to the terms and conditions of Free Domain domain names
   the registrant is BV Dot TK
```

but it is parsed as existed domain

```
{
  "domain": {
    "domain": "aaaa.tk",
    "punycode": "aaaa.tk",
    "name": "aaaa",
    "extension": "tk",
    "name_servers": [
      "ns01.freenom.com",
      "ns02.freenom.com",
      "ns03.freenom.com",
      "ns04.freenom.com"
    ]
  },
  "registrant": {
    "name": "Dot TK administrator",
    "organization": "BV Dot TK",
    "street": "P.O. Box 11774, 1001 GT  Amsterdam, Netherlands",
    "phone": "+31 20 5315725",
    "fax": "+31 20 5315721",
    "email": "abuse: abuse@freenom.com, copyright infringement: copyright@freenom.com"
  }
}
```

Any ideas how to fix it?

**Comment by AlexBlack772** [comment]
It seems it was a bug in .tk tld whois server, now it responses with a correct info

```
whois aaaa.tk
The domain you requested is not known in Freenoms database.

WHOIS query rejected for the Dot TK Domain Registry
```

**Comment by likexian** [comment]
> I noticed that whois server for .tk tld responses for not existed domain with answer that parsed as existed domain
> 
> For example, domain aaaa.tk is not exists
> 
> ```
>    Domain name:
>       AAAA.TK
> 
>    Organisation:
>       BV Dot TK
>       Dot TK administrator
>       P.O. Box 11774
>       1001 GT  Amsterdam
>       Netherlands
>       Phone: +31 20 5315725
>       Fax: +31 20 5315721
>       E-mail: abuse: abuse@freenom.com, copyright infringement: copyright@freenom.com
> 
>    Domain Nameservers:
>       NS01.FREENOM.COM
>       NS02.FREENOM.COM
>       NS03.FREENOM.COM
>       NS04.FREENOM.COM
> 
> 
>    Your selected domain name is a Free Domain. That means that,
>    according to the terms and conditions of Free Domain domain names
>    the registrant is BV Dot TK
> ```
> 

According to the information below, it is really a EXISTS domain.

**Comment by likexian** [comment]
> It seems it was a bug in .tk tld whois server, now it responses with a correct info
> 
> ```
> whois aaaa.tk
> The domain you requested is not known in Freenoms database.
> 
> WHOIS query rejected for the Dot TK Domain Registry
> ```

Well...

**Comment by AlexBlack772** [comment]
sorry, I was in a hurry to post this issue, please close it.

**Comment by likexian** [comment]
OK, any question please open a new issue.

---
*If you think this repository is helpful, please share it with friends, thanks.*
