### ISSUE TITLE
Reliable non existing  domain detection

### ISSUE THREAD

**Issue by AlexBlack772** [likexian/whois-parser#42]
The library relays on word like "not found" to detect non existing domains.
but, for example, .it tld does't have such words. I belive we need a method to detect such domains. We can do this in prepareXX method, or introduce net method (for example precheckXX)

```
whois aaadjdhfhfhssssfh.it
Domain:             aaadjdhfhfhssssfh.it
Status:             AVAILABLE

{
  "domain": {
    "domain": "aaadjdhfhfhssssfh.it",
    "punycode": "aaadjdhfhfhssssfh.it",
    "name": "aaadjdhfhfhssssfh",
    "extension": "it",
    "status": [
      "available"
    ]
  }
}
```

```whois agrigento.it
[Querying whois.nic.it]
[whois.nic.it]
Domain:             agrigento.it
Status:             UNASSIGNABLE


{
  "domain": {
    "domain": "agrigento.it",
    "punycode": "agrigento.it",
    "name": "agrigento",
    "extension": "it",
    "status": [
      "unassignable"
    ]
  }
}

```

what do you think?

**Comment by likexian** [comment]
Hello @AlexBlack772 
Thanks for your feedback.
I think it is too heavy to implement with `prepareXX ` or `precheckXX`, it is more acceptable that to improve `isDomainNotFound`.

---
*If you think this repository is helpful, please share it with friends, thanks.*

**Comment by AlexBlack772** [comment]
>it is more acceptable that to improve isDomainNotFound.

this is a possible way, but in this case we need another algorithm of isDomainNotFound calling.

now, isDomainNotFound is called from getDomainErrorType. But getDomainErrorType is called only if we can't detect domain name.

With .it tld we can detect domain name and getDomainErrorType is not called

**Comment by likexian** [comment]
Yes, you are right, let me think about it.

---
*If you think this repository is helpful, please share it with friends, thanks.*

**Comment by AlexBlack772** [comment]
JFYI, the same issue with .nl tld

sometimes it responds with the following text

```

whois.domain-registry.nl: Server too busy, try again later

```

**Comment by likexian** [comment]
Hello @AlexBlack772 
It works. Please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
