### ISSUE TITLE
feature: Parsing dates

### ISSUE THREAD

**Issue by DSpeichert** [likexian/whois-parser#45]
Dates returned in parsed response, `created_date` and `expiration_date` are strings left as-received from the whois server.

The format returned by each whois server/TLD unfortunately varies.

I think it would be amazing if this library could also include a decoding capability to return maybe `time.Time` for these two fields instead.

**Comment by likexian** [comment]
Hello @DSpeichert 
Thanks for your advise, I do have plan to do it.

**Comment by likexian** [comment]
Hello @DSpeichert 
Sorry for the long delay, @firefart has implemented it, please try the latest version.

refer: https://github.com/likexian/whois-parser/pull/49

---
*If you think this repository is helpful, please share it with friends, thanks.*
