### ISSUE TITLE
.jp TLD partial parsing

### ISSUE THREAD

**Issue by davem14** [likexian/whois-parser#48]
Parsing .jp response is missing some fields with Japanese characters.
> **example:**
> Domain Information: [ドメイン情報]
> [Domain Name]                   GOOGLE.JP
> 
> [登録者名]                      Google LLC
> [Registrant]                    Google LLC
> 
> [Name Server]                   ns1.google.com
> [Name Server]                   ns2.google.com
> [Name Server]                   ns3.google.com
> [Name Server]                   ns4.google.com
> [Signing Key]                   
> 
> [登録年月日]                    2005/05/30
> [有効期限]                      2022/05/31
> [状態]                          Active
> [最終更新]                      2021/06/01 01:05:09 (JST)
> 
> Contact Information: [公開連絡窓口]
> [名前]                          Google LLC
> [Name]                          Google LLC
> [Email]                         dns-admin@google.com
> [Web Page]                       
> [郵便番号]                      94043
> [住所]                          Mountain View
>                                 1600 Amphitheatre Parkway
>                                 CA
> [Postal Address]                Mountain View
>                                 1600 Amphitheatre Parkway
>                                 CA
> [電話番号]                      16502530000
> [FAX番号]                       16502530001
> 
> **parsed:**
> {"domain":{"domain":"google.jp","punycode":"google.jp","name":"google","extension":"jp","name_servers":["ns1.google.com","ns2.google.com","ns3.google.com","ns4.google.com"]},"registrant":{"name":"Google LLC"},"administrative":{"name":"Google LLC","street":"Mountain View, 1600 Amphitheatre Parkway, CA","email":"dns-admin@google.com"}}
> missed: postal code, Created on, Expires on, and more...
> 
> **compare the English only response:**
> Domain Information:
> 
> [Domain Name]                   GOOGLE.JP
> 
> [Registrant]                    Google LLC
> 
> [Name Server]                   ns1.google.com
> [Name Server]                   ns2.google.com
> [Name Server]                   ns3.google.com
> [Name Server]                   ns4.google.com
> [Signing Key]                   
> 
> [Created on]                    2005/05/30
> [Expires on]                    2022/05/31
> [Status]                        Active
> [Last Updated]                  2021/06/01 01:05:09 (JST)
> 
> Contact Information:
> [Name]                          Google LLC
> [Email]                         dns-admin@google.com
> [Web Page]                       
> [Postal code]                   94043
> [Postal Address]                Mountain View
>                                 1600 Amphitheatre Parkway
>                                 CA
> [Phone]                         16502530000
> [Fax]                           16502530001
> 
>

**Comment by likexian** [comment]
Hello @davem14 
Yes, the parser do not handle Japanese characters, please using /e when doing whois query.
