### ISSUE TITLE
Parsing whois.iis.se responses when the domain is not found fails to return ErrNotFoundDomain

### ISSUE THREAD

**Issue by linkdata** [likexian/whois-parser#56]
The response from `whois.iis.se` for the domain `doesnotexist.se`, leading `#` comments removed:
```
domain "doesnotexist.se" not found.
```

Result of calling `whoisparser.Parse("domain \"doesnotexist.se\" not found.")`

```json
{
  "domain": {
    "name": "\"doesnotexist",
    "extension": "se\""
  }
}
```

Run it on the playgound: https://play.golang.com/p/b3dcwFveAiS

**Comment by likexian** [comment]
Hello @linkdata
Thanks for your feedback and PRs https://github.com/likexian/whois-parser/pull/58.
