### ISSUE TITLE
Add support for more layouts when parsing times

### ISSUE THREAD

**Issue by romaincointepas** [likexian/whois-parser#66]
**whois.dns.pl**
```
created:               2002.09.19 13:00:00
```
Suggested layout: `2006.01.02 15:04:05`

---

**whois.dns.be**
```
Registered:	Tue Dec 6 2000
```
Suggested layout: `Mon Jan _2 2006`

---

**whois.jprs.jp**
```
[Registered Date]               2001/03/22
```
Suggested layout: `2006/01/02`

**Comment by likexian** [comment]
Hello @romaincointepas 
It is now supported, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
