### ISSUE TITLE
Parse err

### ISSUE THREAD

**Issue by godzeo** [likexian/whois-parser#68]
if raw, rawErr := whois.Whois("42.99.140.18"); rawErr != nil {
		fmt.Println(rawErr)
	} else {
		fmt.Println(raw)
		if result, err := whoisparser.Parse(raw); err != nil {
			fmt.Println(err)
		} else {
			fmt.Println(result.Domain.Status)
			fmt.Println(result.Domain.UpdatedDate)
			fmt.Println(result.Domain.ExpirationDate)
			fmt.Println(result.Domain.NameServers)
			fmt.Println(result.Registrar.Name)
			fmt.Println(result.Registrar.ReferralURL)
		}
	}
	return

![image](https://github.com/likexian/whois-parser/assets/64398024/32b076af-9ac8-49f3-adeb-da5f89599394)

**Comment by max-rocket-internet** [comment]
Same for me, does not work.

**Comment by likexian** [comment]
Hello @godzeo @max-rocket-internet 
Parsing for IP is not supported yet.

---
*If you think this repository is helpful, please share it with friends, thanks.*

**Comment by likexian** [comment]
refer: https://github.com/likexian/whois-parser/issues/19
