### ISSUE TITLE
parser err

### ISSUE THREAD

**Issue by TI4NLI4NG** [likexian/whois-parser#71]
For some domain name registration information parsing of .jp, a lot of information will be lost.

**Comment by likexian** [comment]
Hello @TI4NLI4NG 
Please post the example.

**Comment by TI4NLI4NG** [comment]
![image](https://github.com/likexian/whois-parser/assets/44729282/be528b10-c95a-4e57-aa24-96113789a9e8)

**Comment by likexian** [comment]
Hello @TI4NLI4NG 
For `.jp`, please append the `/e` to domain.
Change `baidu.jp` to `baidu.jp/e` for example.

---
*If you think this repository is helpful, please share it with friends, thanks.*
