### ISSUE TITLE
.dk incorrectly parsing of ATTENTION

### ISSUE THREAD

**Issue by eyJhb** [likexian/whois-parser#77]
PR #76 fixed parsing of DK domains, however, it introduced a bug where the `attention` field is put into `email`, however that is not always the case that `attention` is an email at all, and could just be a name of a `attention` person.

I'm not sure where to place `attention` instead, and I'll open another PR once a good suggestion has been made.

**Comment by likexian** [comment]
Hello @eyJhb 
I have remove the code about `putting attention into email`.

---
*If you think this repository is helpful, please share it with friends, thanks.*

**Comment by eyJhb** [comment]
Appreciated, thank you! :)
