### ISSUE TITLE
Version() returns 1.24.8 instead of 1.24.15

### ISSUE THREAD

**Issue by ugexe** [likexian/whois-parser#80]
https://github.com/likexian/whois-parser/releases/tag/v1.24.15
https://github.com/likexian/whois-parser/blob/aac2045f6faaa237831d7759a49354fe1950cf48/parser.go#L32-L34

**Comment by likexian** [comment]
Hello @ugexe 
I have fixed it, please try 1.24.16.

---
*If you think this repository is helpful, please share it with friends, thanks.*
